;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	copilot-accept-completion
	elpy-nav-forward-indent
	indent-for-tab-command
	markdown-outdent-or-delete
	multiple-cursors-mode
	sgml-slash
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	))
