;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	comment-dwim
	copilot-accept-completion
	electric-newline-and-maybe-indent
	electric-pair-delete-pair
	elpy-nav-backward-indent
	elpy-nav-forward-indent
	indent-for-tab-command
	markdown-outdent-or-delete
	multiple-cursors-mode
	sgml-slash
	treemacs-leftclick-action
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	magit-status
	))
